highlighter: pygments
# safe: true
lsi: false
permalink: "/:title"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
